### ISSUE TITLE
why compile cuda source 

### ISSUE THREAD

**Issue by newjavaer** [perrying/ssn-pytorch#1]
why compile cuda source 
 something wrong in the "from lib.ssn.ssb import sparse_ssn_iter"?why?
should i compile the ssn firstly?

**Comment by perrying** [comment]
It complies ```pair_wise_distance_cuda_source.py``` by ```torch.utils.cpp_extension.load_inline``` function.
https://github.com/perrying/ssn-pytorch/blob/ad45991754b62696164849a6a58a2d6badb86205/lib/ssn/pair_wise_distance.py#L7

If you'd like to avoid compiling it every runtime, you make ```.cu``` file from ```pair_wise_distance_cuda_source.py``` and compile it following https://pytorch.org/tutorials/advanced/cpp_extension.html

**Comment by tarun005** [comment]
How do I make a cu file and compile it? Can you help a bit more with that?
