### ISSUE TITLE
the reconstructed features may have been calculated incorrectly

### ISSUE THREAD

**Issue by Haojia521** [perrying/ssn-pytorch#3]
https://github.com/perrying/ssn-pytorch/blob/25c69d341beb412a9b5cd62dd92a3ae11b9d2971/lib/utils/loss.py#L49-L53

I have a question with line 53 in lib/utils/loss.py. According the paper 'superpixel sampling networks', the reconstructed pixel features are ![](http://latex.codecogs.com/gif.latex?R^{*}=\widetilde{Q}\widehat{Q}^{T}R), and ![](http://latex.codecogs.com/gif.latex?\widetilde{Q}) means the row-normalized association matrix Q. however, the code in line 53 seems not using row-normalized Q but the Q itself to compute the reconstructed label.

**Comment by yueyu-stu** [comment]
In my view, assignment is a column-normalized matrix, and permuted assignment is the transpose matrix of assignment, meaning that permuted assignment is a row-normalized matrix.

**Comment by Haojia521** [comment]
if the assignment is a column-normalized matrix, the calculation of super-pixel feature should be torch.bmm(assignment, pixel_feat). however, the codes show that super-pixel feature is calculated by torch.bmm(assignment, pixel_feat) / assignment.sum(dim=2)

https://github.com/perrying/ssn-pytorch/blob/25c69d341beb412a9b5cd62dd92a3ae11b9d2971/lib/utils/loss.py#L48-L53

so i am confused why line 48 uses normalized assignment but line 53 not

**Comment by yueyu-stu** [comment]
Here is a simple example.
Assignment is a column-normalized ($nspix \times npix$) matrix, so column #j is the probability of pixel #j belonging to each spixel. Row #i of assignment is the cardinality of the spixel #i, like $(1, 1, 1, 0, \ldots, 0)$ means that the first 3 pixels belong to spixel #i (though they may not be 1).
Column #k of permuted label (`labels` in Line 48) means that each pixel belongs to class #k or not. If the cluster is of precision and belongs to class #k, column #k should be $(1, 1, 1, 0, \ldots, 0)^\mathrm{T}$.
After multiplication, the (i, k) element of `spixelWithoutMean` (if `spixel_mean` is not be divided by `assignment.sum(...)`) is 3. But this matrix represents probability, meaning that each element should be not greater than 1. So this matrix should be divided by the cardinality of spixels.
As for Line 53, `permuted_assignment` is a row-normalized matrix, so the sum of each row (dim is 2) is 1. Besides, it is on the left side, meaning that it is not necessary to obtain a sum vector.

**Comment by Haojia521** [comment]
ok, i see. thanks a lot for your reply.
